# distillation
student_lr: 0.0001
teacher_lr: 0.0001
batch_size: 128
student_epochs: 1
teacher_epochs: 1
meta_epochs: 2
alpha: 0.5
beta: 0.5
t: 3

# data set split
train_split: 0.4
early_stopping_split: 0.2
val_split: 0.2
test_split: 0.2


# WandB Proj Name
proj_name: "Test"


