# reproducability
seed: 420

# distillation
student_lr: 0.0001
teacher_lr: 0.0001
batch_size: 128
student_epochs: 2
teacher_epochs: 3
meta_epochs: 20
alpha: 0.5
beta: 0.5


# data set split
train_split: 0.4
early_stopping_split: 0.2
val_split: 0.2
test_split: 0.2


# WandB Proj Name
proj_name: "Proof of Concept"

# specify models
# choose teachers from "MLP1Layer", "MLP2Layer", "MLP5Layer" or save your own model in src/Models/Teachers.py
# and give your model a name and call it via the main function.
# choose students from "MLP1Layer", "transformer" or save your own model in src/Models/Students.py
# and give your model a name and call it via the main function.

teacher: "MLP1Layer"
student: "transformer"

